# Generated by Django 4.2.2 on 2023-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="static\\images\\defaultpic.jpg", null=True, upload_to=""
            ),
        ),
    ]
