# Generated by Django 4.2.2 on 2023-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(default="This is my bio, haven't updated yet :)"),
        ),
    ]
